(function(){
  'use strict';
  const dist=(a,b,c,d)=>Math.hypot(a-c,b-d);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const deep=v=>JSON.parse(JSON.stringify(v));
  function nearestOnSegment(px,py,a,b){const vx=b[0]-a[0],vy=b[1]-a[1],den=vx*vx+vy*vy||1;const t=clamp(((px-a[0])*vx+(py-a[1])*vy)/den,0,1);const x=a[0]+vx*t,y=a[1]+vy*t;return {x,y,t,d:dist(px,py,x,y)}}

  const HandleStore={
    db:null,
    async open(){if(this.db)return this.db;this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open('esposizione-test-editor',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('handles'))r.result.createObjectStore('handles')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return this.db},
    async get(key){try{const db=await this.open();return await new Promise((resolve,reject)=>{const r=db.transaction('handles').objectStore('handles').get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}catch(_){return null}},
    async set(key,value){try{const db=await this.open();await new Promise((resolve,reject)=>{const tx=db.transaction('handles','readwrite');tx.objectStore('handles').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(_){}}
  };

  class Editor{
    constructor(game,els){
      this.game=game;this.els=els;this.enabled=false;this.prevDebug=false;this.mode='select';this.draft=[];this.drag=null;this.pan=null;this.selected=null;this.rectStart=null;
      this.undoStack=[];this.redoStack=[];this.dirty=false;this.dragHistoryArmed=false;this.fileHandles={};this.panelLocked=false;this.panelDrag=null;this.lastPointer=null;this.speedFactor=1;
      this.visibility={collisions:true,gates:true,hotspots:true,decor:true};
      this.bind();this.restorePanelPosition();this.loadSavedHandles();
    }
    bind(){
      const c=this.game.canvas;
      c.addEventListener('pointerdown',e=>this.pointerDown(e));c.addEventListener('pointermove',e=>this.pointerMove(e));c.addEventListener('pointerup',e=>this.pointerUp(e));c.addEventListener('pointercancel',e=>this.pointerUp(e));c.addEventListener('wheel',e=>this.wheel(e),{passive:false});
      c.addEventListener('dblclick',e=>{if(this.enabled&&['obstacle','walkable'].includes(this.mode)){e.preventDefault();this.finishDraft()}});c.addEventListener('contextmenu',e=>{if(this.enabled){e.preventDefault();this.finishDraft()}});
      window.addEventListener('keydown',e=>{if(!this.enabled)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();this.redo();return}if(e.key==='Enter')this.finishDraft();if(e.key==='Backspace'){e.preventDefault();this.draft.pop()}if(e.key==='Delete')this.deleteSelected()});

      this.els.close.onclick=()=>this.toggle(false);
      this.els.select.onclick=()=>this.setMode('select');
      this.els.obstacle.onclick=()=>this.setMode('obstacle');this.els.walkable.onclick=()=>this.setMode('walkable');this.els.point.onclick=()=>this.setMode('point');
      this.els.gateArea.onclick=()=>this.setMode('gate-area');this.els.gateBoat.onclick=()=>this.setMode('gate-boat');this.els.gateExit.onclick=()=>this.setMode('gate-exit');
      this.els.hotspot.onclick=()=>this.setMode('hotspot');this.els.decor.onclick=()=>this.setMode('decor');this.els.palm.onclick=()=>this.setMode('palm');this.els.setSpawn.onclick=()=>this.setMode('spawn');this.els.teleport.onclick=()=>this.setMode('teleport');
      this.els.finish.onclick=()=>this.finishDraft();this.els.removePoint.onclick=()=>this.removeSelectedPoint();this.els.remove.onclick=()=>this.deleteSelected();
      this.els.undoHistory.onclick=()=>this.undo();this.els.redoHistory.onclick=()=>this.redo();
      this.els.scaleDown.onclick=()=>this.scaleSelected(1/1.08);this.els.scaleUp.onclick=()=>this.scaleSelected(1.08);this.els.anchorDown.onclick=()=>this.adjustAnchor(-.02);this.els.anchorUp.onclick=()=>this.adjustAnchor(.02);
      this.els.rotateLeft.onclick=()=>this.rotateSelected(-5);this.els.rotateRight.onclick=()=>this.rotateSelected(5);this.els.duplicateDecor.onclick=()=>this.duplicateDecor();
      this.els.gateEdit.onclick=()=>this.editSelectedGate();this.els.gateWDown.onclick=()=>this.resizeGate(.9,1);this.els.gateWUp.onclick=()=>this.resizeGate(1.1,1);this.els.gateHDown.onclick=()=>this.resizeGate(1,.9);this.els.gateHUp.onclick=()=>this.resizeGate(1,1.1);
      this.els.hotspotEdit.onclick=()=>this.editSelectedHotspot();this.els.hotspotRadiusDown.onclick=()=>this.resizeHotspot(.9);this.els.hotspotRadiusUp.onclick=()=>this.resizeHotspot(1.1);
      this.els.zoomOut.onclick=()=>this.changeZoom(1/1.12);this.els.zoomIn.onclick=()=>this.changeZoom(1.12);this.els.zoomReset.onclick=()=>this.setZoom(1);this.els.centerPlayer.onclick=()=>this.centerPlayer();this.els.centerPlayer2.onclick=()=>this.centerPlayer();
      this.els.toggleCollisions.onclick=()=>this.toggleLayer('collisions',this.els.toggleCollisions,'Collisioni');this.els.toggleGates.onclick=()=>this.toggleLayer('gates',this.els.toggleGates,'Varchi');this.els.toggleHotspots.onclick=()=>this.toggleLayer('hotspots',this.els.toggleHotspots,'Hotspot');this.els.toggleDecor.onclick=()=>this.toggleLayer('decor',this.els.toggleDecor,'Decor');
      this.els.speed1.onclick=()=>this.setSpeed(1);this.els.speed2.onclick=()=>this.setSpeed(2);this.els.speed4.onclick=()=>this.setSpeed(4);
      this.els.export.onclick=()=>this.exportJSON();this.els.importBtn.onclick=()=>this.els.importInput.click();this.els.importInput.onchange=e=>this.importJSON(e.target.files?.[0]);
      this.els.decorExport.onclick=()=>this.exportDecor();this.els.decorImportBtn.onclick=()=>this.els.decorImportInput.click();this.els.decorImportInput.onchange=e=>this.importDecor(e.target.files?.[0]);
      this.els.copyJSON.onclick=()=>this.copyJSON();this.els.linkJSON.onclick=()=>this.linkJSON();this.els.saveCurrent.onclick=()=>this.saveCurrentJSON();
      this.els.panelReset.onclick=()=>this.resetPanelPosition();this.els.resetPanel.onclick=()=>this.resetPanelPosition();this.els.panelCompact.onclick=()=>this.toggleCompact();this.els.panelLock.onclick=()=>this.togglePanelLock();this.els.lockPanel.onclick=()=>this.togglePanelLock();
      this.bindPanelDrag();
    }
    async loadSavedHandles(){for(const id of ['nord','sud']){const h=await HandleStore.get(`json-${id}`);if(h)this.fileHandles[id]=h}this.refreshFileState()}
    bindPanelDrag(){const h=this.els.dragHandle,p=this.els.panel;if(!h||!p)return;h.addEventListener('pointerdown',e=>{if(this.panelLocked||e.button!==0||e.target.closest('button'))return;const r=p.getBoundingClientRect();this.panelDrag={id:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top};h.setPointerCapture?.(e.pointerId);h.classList.add('dragging');e.preventDefault()});h.addEventListener('pointermove',e=>{if(!this.panelDrag||this.panelDrag.id!==e.pointerId)return;this.movePanel(e.clientX-this.panelDrag.dx,e.clientY-this.panelDrag.dy)});const end=e=>{if(!this.panelDrag||this.panelDrag.id!==e.pointerId)return;this.panelDrag=null;h.classList.remove('dragging');this.savePanelPosition()};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)}
    movePanel(left,top){const p=this.els.panel,frame=document.querySelector('#gameFrame');const fr=frame?.getBoundingClientRect()||{width:innerWidth,height:innerHeight,left:0,top:0};const pr=p.getBoundingClientRect();const x=clamp(left-fr.left,0,Math.max(0,fr.width-pr.width)),y=clamp(top-fr.top,0,Math.max(0,fr.height-pr.height));p.style.left=`${Math.round(x)}px`;p.style.top=`${Math.round(y)}px`;p.style.right='auto'}
    savePanelPosition(){localStorage.setItem('esposizione-test-panel-pos',JSON.stringify({left:this.els.panel.style.left,top:this.els.panel.style.top}))}
    restorePanelPosition(){try{const p=JSON.parse(localStorage.getItem('esposizione-test-panel-pos')||'null');if(p?.left)this.els.panel.style.left=p.left;if(p?.top)this.els.panel.style.top=p.top}catch(_){}}
    resetPanelPosition(){this.els.panel.style.left='14px';this.els.panel.style.top='82px';this.els.panel.style.right='auto';localStorage.removeItem('esposizione-test-panel-pos');this.updateStatus('Posizione pannello ripristinata')}
    toggleCompact(){this.els.panel.classList.toggle('compact')}
    togglePanelLock(){this.panelLocked=!this.panelLocked;this.els.lockPanel.textContent=this.panelLocked?'🔒':'🔓';this.els.panelLock.textContent=this.panelLocked?'Sblocca pannello':'Blocca pannello';this.updateStatus(this.panelLocked?'Pannello bloccato':'Pannello sbloccato')}

    toggle(v=!this.enabled){if(v){this.prevDebug=this.game.debug;this.game.debug=true;this.game.viewZoom=1}else{this.game.debug=this.prevDebug}this.enabled=v;this.els.panel.hidden=!v;document.querySelector('#gameFrame')?.classList.toggle('editor-on',v);this.game.setEditorActive(v);this.draft=[];this.drag=null;this.pan=null;this.selected=null;this.rectStart=null;if(v){this.game.clampCamera();this.refreshMeta();this.refreshFileState();this.updateStatus('TEST attiva · pannello trascinabile · strumenti raccolti per categoria');this.updateCoords(null)}else this.refreshSelected()}
    setMode(m){this.mode=m;this.draft=[];this.drag=null;this.pan=null;this.rectStart=null;this.highlightButtons();this.updateStatus(this.modeLabel())}
    modeLabel(){return {select:'Seleziona/sposta elementi · trascina lo sfondo per spostare la mappa',obstacle:'Nuovo ostacolo ROSSO · clic sui vertici · doppio clic/INVIO per chiudere',walkable:'Nuova area VERDE percorribile · clic sui vertici · doppio clic/INVIO per chiudere',point:'Aggiungi punto · clic sul bordo rosso/verde','gate-area':'Varco Area · due clic sugli angoli opposti','gate-boat':'Varco Battello · due clic sugli angoli opposti','gate-exit':'Varco Uscita · due clic sugli angoli opposti',hotspot:'Aggiungi hotspot · un clic',decor:'Lampione · clic sulla mappa',palm:'Palma · clic sulla mappa',spawn:'Imposta Spawn · clic sulla mappa',teleport:'Teletrasporta giocatore · clic sulla mappa'}[this.mode]||this.mode}
    highlightButtons(){for(const [m,el] of [['select',this.els.select],['obstacle',this.els.obstacle],['walkable',this.els.walkable],['point',this.els.point],['gate-area',this.els.gateArea],['gate-boat',this.els.gateBoat],['gate-exit',this.els.gateExit],['hotspot',this.els.hotspot],['decor',this.els.decor],['palm',this.els.palm],['spawn',this.els.setSpawn],['teleport',this.els.teleport]])if(el)el.classList.toggle('active',m===this.mode)}
    screen(e){const r=this.game.canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*(this.game.canvas.width/r.width),y:(e.clientY-r.top)*(this.game.canvas.height/r.height)}}
    world(e){const s=this.screen(e),z=this.game.viewZoom||1;return {x:Math.round(this.game.camera.x+s.x/z),y:Math.round(this.game.camera.y+s.y/z)}}
    updateCoords(p){if(p)this.lastPointer=p;const z=Math.round((this.game.viewZoom||1)*100),q=p||this.lastPointer;this.els.coords.textContent=q?`x ${q.x} · y ${q.y} · zoom ${z}%`:`x — · y — · zoom ${z}%`;this.refreshMeta()}
    refreshMeta(){if(this.els.area)this.els.area.textContent=`${this.game.area?.title||'AREA'} · ${this.game.areaId?.toUpperCase()||''}`;this.refreshSelected()}
    refreshSelected(){if(!this.els.selected)return;let text='Elemento: nessuno';if(this.selected){const s=this.selected;if(s.group==='obstacle')text=`Elemento: Ostacolo #${s.index+1}${Number.isInteger(s.vertex)?` · punto ${s.vertex+1}`:''}`;else if(s.group==='walkable')text=`Elemento: Percorribile #${s.index+1}${Number.isInteger(s.vertex)?` · punto ${s.vertex+1}`:''}`;else if(s.group==='gate')text=`Elemento: Varco ${s.obj.type||'area'} · ${s.obj.id||s.index+1}`;else if(s.group==='hotspot')text=`Elemento: Hotspot · ${s.obj.title||s.obj.id}`;else if(s.group==='decor')text=`Elemento: Decor · ${s.obj.id}`;}this.els.selected.textContent=text}
    setDirty(v=true){this.dirty=v;this.els.saveState.className=`save-state ${v?'dirty':'clean'}`;this.els.saveState.textContent=v?'● Modifiche non salvate':'✓ Salvato';}
    areaState(){const a=this.game.area;return deep({spawn:a.spawn,walkable:a.walkable,obstacles:a.obstacles,hotspots:a.hotspots,gates:a.gates,decor:a.decor||[]})}
    applyState(st){const a=this.game.area;a.spawn=deep(st.spawn);a.walkable=deep(st.walkable);a.obstacles=deep(st.obstacles);a.hotspots=deep(st.hotspots);a.gates=deep(st.gates);a.decor=deep(st.decor||[]);this.selected=null;this.refreshSelected();this.setDirty(true)}
    beginChange(){this.undoStack.push(this.areaState());if(this.undoStack.length>80)this.undoStack.shift();this.redoStack=[]}
    undo(){if(!this.undoStack.length){this.updateStatus('Niente da annullare');return}this.redoStack.push(this.areaState());this.applyState(this.undoStack.pop());this.updateStatus('Ultima modifica annullata')}
    redo(){if(!this.redoStack.length){this.updateStatus('Niente da ripetere');return}this.undoStack.push(this.areaState());this.applyState(this.redoStack.pop());this.updateStatus('Modifica ripristinata')}

    pointerDown(e){if(!this.enabled||e.button!==0)return;const p=this.world(e);this.updateCoords(p);
      if(this.mode==='obstacle'||this.mode==='walkable'){this.draft.push([p.x,p.y]);return}
      if(this.mode==='point'){this.addPointOnEdge(p);return}
      if(this.mode.startsWith('gate-')){if(!this.rectStart){this.rectStart=p;this.updateStatus('Varco: scegli l’angolo opposto')}else{this.addGate(this.rectStart,p,this.mode.slice(5));this.rectStart=null;this.setMode('select')}return}
      if(this.mode==='hotspot'){this.addHotspot(p);this.setMode('select');return}
      if(this.mode==='decor'){this.addDecor(p);return}
      if(this.mode==='palm'){this.addPalm(p);return}
      if(this.mode==='spawn'){this.beginChange();this.game.area.spawn={x:p.x,y:p.y};this.setDirty(true);this.updateStatus(`Spawn ${this.game.area.title}: ${p.x}, ${p.y}`);this.setMode('select');return}
      if(this.mode==='teleport'){this.game.player.x=p.x;this.game.player.y=p.y;this.game.clampCamera();this.updateStatus(`Giocatore spostato: ${p.x}, ${p.y}`);this.setMode('select');return}
      if(this.pick(p)){this.dragHistoryArmed=true;return}
      const s=this.screen(e);this.pan={pointerId:e.pointerId,lastX:s.x,lastY:s.y};this.game.canvas.setPointerCapture?.(e.pointerId);document.querySelector('#gameFrame')?.classList.add('editor-panning');this.updateStatus('Spostamento mappa · rilascia il mouse per fermarti')
    }
    pointerMove(e){if(!this.enabled)return;const p=this.world(e);this.updateCoords(p);if(this.pan&&this.pan.pointerId===e.pointerId){const s=this.screen(e),z=this.game.viewZoom||1,dx=s.x-this.pan.lastX,dy=s.y-this.pan.lastY;this.game.camera.x-=dx/z;this.game.camera.y-=dy/z;this.pan.lastX=s.x;this.pan.lastY=s.y;this.game.clampCamera();return}if(this.drag){if(this.dragHistoryArmed){this.beginChange();this.dragHistoryArmed=false}const obj=this.drag.obj;if(this.drag.kind==='vertex'){obj.points[this.drag.vertex]=[p.x,p.y]}else if(this.drag.kind==='circle'){obj.x=p.x;obj.y=p.y}else if(this.drag.kind==='gate'){obj.x=Math.round(p.x-this.drag.dx);obj.y=Math.round(p.y-this.drag.dy)}else if(this.drag.kind==='hotspot'||this.drag.kind==='decor'){obj.x=p.x;obj.y=p.y}this.setDirty(true);this.refreshSelected()}}
    pointerUp(e){this.drag=null;this.dragHistoryArmed=false;if(this.pan&&(!e||this.pan.pointerId===e.pointerId)){try{this.game.canvas.releasePointerCapture?.(this.pan.pointerId)}catch(_){}this.pan=null;document.querySelector('#gameFrame')?.classList.remove('editor-panning');if(this.mode==='select')this.updateStatus(this.modeLabel())}}
    wheel(e){if(!this.enabled)return;e.preventDefault();const s=this.screen(e),old=this.game.viewZoom||1,factor=e.deltaY<0?1.12:1/1.12,next=clamp(old*factor,.35,3.2);if(Math.abs(next-old)<.0001)return;const worldX=this.game.camera.x+s.x/old,worldY=this.game.camera.y+s.y/old;this.game.viewZoom=next;this.game.camera.x=worldX-s.x/next;this.game.camera.y=worldY-s.y/next;this.game.clampCamera();this.updateCoords(this.world(e));this.updateStatus(`Zoom ${Math.round(next*100)}%`)}
    setZoom(v){this.game.viewZoom=clamp(v,.35,3.2);this.game.clampCamera();this.updateCoords(null)}changeZoom(f){this.setZoom((this.game.viewZoom||1)*f)}centerPlayer(){this.game.cameraToPlayer();this.updateStatus('Vista centrata sul giocatore')}
    toggleLayer(key,btn,label){this.visibility[key]=!this.visibility[key];btn.classList.toggle('active',this.visibility[key]);btn.textContent=`${label} ${this.visibility[key]?'ON':'OFF'}`}
    setSpeed(f){this.speedFactor=f;this.game.player.speed=275*f;for(const [n,b] of [[1,this.els.speed1],[2,this.els.speed2],[4,this.els.speed4]])b.classList.toggle('active',n===f);this.updateStatus(`Velocità TEST ${f}×`)}

    polyGroups(){const a=this.game.area;return [['obstacle',a.obstacles],['walkable',(a.walkable||[]).map(points=>({type:'poly',points}))]]}
    decorBounds(o){const sc=o.scale||1,w=(o.width||43)*sc,h=(o.height||101)*sc,ax=o.anchorX??.5,ay=o.anchorY??1;return {x:o.x-w*ax,y:o.y-h*ay,w,h}}
    pick(p){const a=this.game.area,near=18/(this.game.viewZoom||1);for(const [group,list] of this.polyGroups()){for(let i=0;i<list.length;i++){const o=list[i];if(o.type==='poly'){for(let v=0;v<o.points.length;v++){if(dist(p.x,p.y,o.points[v][0],o.points[v][1])<near){this.selected={group,index:i,obj:o,vertex:v};this.drag={kind:'vertex',obj:o,vertex:v};this.updateStatus(`${group} #${i+1} · vertice ${v+1}`);this.refreshSelected();return true}}}else if(o.type==='circle'&&dist(p.x,p.y,o.x,o.y)<o.r+near){this.selected={group,index:i,obj:o};this.drag={kind:'circle',obj:o};this.updateStatus(`Ostacolo circolare #${i+1}`);this.refreshSelected();return true}}}
      for(let i=(a.decor||[]).length-1;i>=0;i--){const o=a.decor[i],b=this.decorBounds(o);if(p.x>=b.x-near&&p.x<=b.x+b.w+near&&p.y>=b.y-near&&p.y<=b.y+b.h+near){this.selected={group:'decor',index:i,obj:o};this.drag={kind:'decor',obj:o};this.updateStatus(`Decor: ${o.id}`);this.refreshSelected();return true}}
      for(let i=0;i<(a.gates||[]).length;i++){const x=a.gates[i];if(p.x>=x.x&&p.x<=x.x+x.w&&p.y>=x.y&&p.y<=x.y+x.h){this.selected={group:'gate',index:i,obj:x};this.drag={kind:'gate',obj:x,dx:p.x-x.x,dy:p.y-x.y};this.updateStatus(`Varco #${i+1} · ${x.type||'area'}`);this.refreshSelected();return true}}
      for(let i=0;i<(a.hotspots||[]).length;i++){const h=a.hotspots[i];if(dist(p.x,p.y,h.x,h.y)<Math.max(35,h.r||0)/(this.game.viewZoom||1)){this.selected={group:'hotspot',index:i,obj:h};this.drag={kind:'hotspot',obj:h};this.updateStatus(`Hotspot: ${h.title}`);this.refreshSelected();return true}}
      this.selected=null;this.refreshSelected();return false
    }
    addPointOnEdge(p){const max=24/(this.game.viewZoom||1);let best=null;for(const [group,list] of this.polyGroups()){for(let i=0;i<list.length;i++){const o=list[i];if(o.type!=='poly'||o.points.length<2)continue;for(let s=0;s<o.points.length;s++){const n=nearestOnSegment(p.x,p.y,o.points[s],o.points[(s+1)%o.points.length]);if(n.d<=max&&(!best||n.d<best.d))best={group,index:i,obj:o,segment:s,...n}}}}if(!best){this.updateStatus('Nessun bordo vicino');return false}this.beginChange();const at=best.segment+1;best.obj.points.splice(at,0,[Math.round(best.x),Math.round(best.y)]);this.selected={group:best.group,index:best.index,obj:best.obj,vertex:at};this.setDirty(true);this.refreshSelected();this.updateStatus(`${best.group} #${best.index+1} · nuovo vertice ${at+1}`);return true}
    removeSelectedPoint(){const s=this.selected;if(!s||!['obstacle','walkable'].includes(s.group)||!s.obj?.points||!Number.isInteger(s.vertex)){this.updateStatus('Seleziona prima un vertice rosso/verde');return}if(s.obj.points.length<=3){this.updateStatus('Un poligono deve mantenere almeno 3 punti');return}this.beginChange();s.obj.points.splice(s.vertex,1);this.selected={group:s.group,index:s.index,obj:s.obj};this.drag=null;this.setDirty(true);this.refreshSelected();this.updateStatus('Punto rimosso')}
    finishDraft(){if(!this.enabled||this.draft.length<3)return;this.beginChange();const a=this.game.area;if(this.mode==='obstacle')a.obstacles.push({type:'poly',label:'editor',points:this.draft.map(p=>[...p])});if(this.mode==='walkable')a.walkable.push(this.draft.map(p=>[...p]));this.draft=[];this.setDirty(true);this.setMode('select')}
    addGate(a,b,type){this.beginChange();const area=this.game.area,x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.max(20,Math.abs(a.x-b.x)),h=Math.max(20,Math.abs(a.y-b.y)),other=area.id==='nord'?'sud':'nord',ts=Date.now();let g;if(type==='area')g={id:`gate-area-${ts}`,type:'area',x,y,w,h,target:other,targetGate:`to-${area.id}`,message:this.game.areas[other]?.title||other};else if(type==='boat')g={id:`boat-${area.id}-${ts}`,type:'boat',x,y,w,h,target:other,targetGate:`boat-${other}`,message:`Battello · Stazione ${area.id==='nord'?'A':'B'}`};else g={id:`exit-${area.id}-${ts}`,type:'exit',x,y,w,h,action:'return-to-games',message:"Uscita dall'Esposizione"};area.gates=area.gates||[];area.gates.push(g);this.selected={group:'gate',index:area.gates.length-1,obj:g};this.setDirty(true);this.refreshSelected()}
    editSelectedGate(){const s=this.selected;if(!s||s.group!=='gate'){this.updateStatus('Seleziona prima un varco');return}const g=s.obj;this.beginChange();const id=prompt('ID varco',g.id);if(id===null){this.undoStack.pop();return}g.id=id||g.id;const msg=prompt('Messaggio',g.message||'');if(msg!==null)g.message=msg;if(g.type!=='exit'){const target=prompt('Area destinazione (nord/sud)',g.target||'');if(target!==null&&target.trim())g.target=target.trim();const tg=prompt('ID varco di arrivo',g.targetGate||'');if(tg!==null)g.targetGate=tg.trim()}this.setDirty(true);this.refreshSelected();this.updateStatus('Varco aggiornato')}
    resizeGate(fw,fh){const s=this.selected;if(!s||s.group!=='gate'){this.updateStatus('Seleziona prima un varco');return}this.beginChange();s.obj.w=Math.max(20,Math.round(s.obj.w*fw));s.obj.h=Math.max(20,Math.round(s.obj.h*fh));this.setDirty(true);this.updateStatus(`Varco ${s.obj.w} × ${s.obj.h}`)}
    addHotspot(p){const title=prompt('Nome hotspot','Punto interattivo')||'Punto interattivo';this.beginChange();const h={id:`hotspot-${Date.now()}`,x:p.x,y:p.y,r:110,title,text:'Hotspot di prova creato in Modalità Test.'};this.game.area.hotspots.push(h);this.selected={group:'hotspot',index:this.game.area.hotspots.length-1,obj:h};this.setDirty(true);this.refreshSelected()}
    editSelectedHotspot(){const s=this.selected;if(!s||s.group!=='hotspot'){this.updateStatus('Seleziona prima un hotspot');return}this.beginChange();const t=prompt('Titolo hotspot',s.obj.title||'');if(t===null){this.undoStack.pop();return}s.obj.title=t;const txt=prompt('Testo hotspot',s.obj.text||'');if(txt!==null)s.obj.text=txt;this.setDirty(true);this.refreshSelected();this.updateStatus('Hotspot aggiornato')}
    resizeHotspot(f){const s=this.selected;if(!s||s.group!=='hotspot'){this.updateStatus('Seleziona prima un hotspot');return}this.beginChange();s.obj.r=clamp(Math.round((s.obj.r||110)*f),20,600);this.setDirty(true);this.updateStatus(`Raggio hotspot: ${s.obj.r}`)}
    addDecor(p){this.beginChange();const o={id:`lampione-${Date.now()}`,kind:'lamp',type:'ysort',asset:'images/decor/centrale/lamps/lampione_01.png',x:p.x,y:p.y,width:43,height:101,anchorX:.5,anchorY:.94,scale:1,rotation:0,collisionRadius:7,animation:null};this.game.area.decor=this.game.area.decor||[];this.game.area.decor.push(o);this.selected={group:'decor',index:this.game.area.decor.length-1,obj:o};this.setDirty(true);this.refreshSelected();this.updateStatus('Lampione aggiunto')}
    addPalm(p){this.beginChange();const frames=['images/decor/centrale/palms/palma_01_01.png','images/decor/centrale/palms/palma_01_02.png','images/decor/centrale/palms/palma_01_03.png'];const o={id:`palma-${Date.now()}`,kind:'palm',type:'ysort',asset:frames[0],x:p.x,y:p.y,width:160,height:218,anchorX:.5,anchorY:.95,scale:1,rotation:0,collisionRadius:13,animation:{frames,fps:2}};this.game.area.decor=this.game.area.decor||[];this.game.area.decor.push(o);this.selected={group:'decor',index:this.game.area.decor.length-1,obj:o};this.setDirty(true);this.refreshSelected();this.updateStatus('Palma aggiunta')}
    scaleSelected(factor){const s=this.selected;if(!s||s.group!=='decor'){this.updateStatus('Seleziona prima un elemento Decor');return}this.beginChange();s.obj.scale=clamp((s.obj.scale||1)*factor,.35,3);this.setDirty(true);this.updateStatus(`Decor · scala ${Math.round(s.obj.scale*100)}%`)}
    adjustAnchor(delta){const s=this.selected;if(!s||s.group!=='decor'){this.updateStatus('Seleziona prima un elemento Decor');return}this.beginChange();s.obj.anchorY=clamp((s.obj.anchorY??1)+delta,.05,1);this.setDirty(true);this.updateStatus(`Decor · anchor ${Math.round(s.obj.anchorY*100)}%`)}
    rotateSelected(delta){const s=this.selected;if(!s||s.group!=='decor'){this.updateStatus('Seleziona prima un elemento Decor');return}this.beginChange();s.obj.rotation=((s.obj.rotation||0)+delta+360)%360;this.setDirty(true);this.updateStatus(`Decor · rotazione ${s.obj.rotation}°`)}
    duplicateDecor(){const s=this.selected;if(!s||s.group!=='decor'){this.updateStatus('Seleziona prima un elemento Decor');return}this.beginChange();const o=deep(s.obj);o.id=`${o.kind||'decor'}-${Date.now()}`;o.x+=30;o.y+=30;this.game.area.decor.push(o);this.selected={group:'decor',index:this.game.area.decor.length-1,obj:o};this.setDirty(true);this.refreshSelected();this.updateStatus('Decorazione duplicata')}
    deleteSelected(){if(!this.selected){this.updateStatus('Nessun elemento selezionato');return}this.beginChange();const a=this.game.area,{group,index}=this.selected;if(group==='obstacle')a.obstacles.splice(index,1);else if(group==='walkable')a.walkable.splice(index,1);else if(group==='gate')a.gates.splice(index,1);else if(group==='hotspot')a.hotspots.splice(index,1);else if(group==='decor')a.decor.splice(index,1);this.selected=null;this.setDirty(true);this.refreshSelected();this.updateStatus('Elemento eliminato')}

    collisionJSON(){const a=this.game.area;return {areaId:a.id,width:a.width,height:a.height,spawn:a.spawn,walkable:a.walkable,obstacles:a.obstacles,hotspots:a.hotspots,gates:a.gates}}
    exportJSON(){const a=this.game.area,out=this.collisionJSON(),blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`area_${a.id}_collisions.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.updateStatus('JSON collisioni esportato')}
    async importJSON(file){if(!file)return;try{const data=JSON.parse(await file.text()),a=this.game.area;this.beginChange();if(data.walkable)a.walkable=data.walkable;if(data.obstacles)a.obstacles=data.obstacles;if(data.hotspots)a.hotspots=data.hotspots;if(data.gates)a.gates=data.gates;else if(data.exits)a.gates=data.exits.map(x=>({...x,type:x.type||'area'}));if(data.spawn)a.spawn=data.spawn;this.setDirty(true);this.selected=null;this.refreshSelected();this.updateStatus('JSON collisioni importato nella mappa corrente')}catch(err){alert('JSON non valido: '+err.message)}this.els.importInput.value=''}
    exportDecor(){const a=this.game.area,out={areaId:a.id,objects:a.decor||[]},blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`area_${a.id}_decor.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.updateStatus('JSON Decor esportato')}
    async importDecor(file){if(!file)return;try{const data=JSON.parse(await file.text()),a=this.game.area;this.beginChange();if(Array.isArray(data.objects))a.decor=data.objects;else if(Array.isArray(data))a.decor=data;this.selected=null;this.setDirty(true);this.refreshSelected();this.updateStatus('JSON Decor importato')}catch(err){alert('JSON Decor non valido: '+err.message)}this.els.decorImportInput.value=''}
    async copyJSON(){const text=JSON.stringify(this.collisionJSON(),null,2);try{await navigator.clipboard.writeText(text);this.updateStatus('JSON copiato negli appunti')}catch(_){this.updateStatus('Impossibile copiare negli appunti')}}
    async linkJSON(){const id=this.game.areaId;if(!window.showOpenFilePicker){this.updateStatus('Collegamento diretto non supportato: usa Esporta JSON');return false}try{const [h]=await window.showOpenFilePicker({multiple:false,types:[{description:'JSON collisioni',accept:{'application/json':['.json']}}]});this.fileHandles[id]=h;await HandleStore.set(`json-${id}`,h);this.refreshFileState();this.updateStatus(`Collegato: ${h.name}`);return true}catch(err){if(err?.name!=='AbortError')this.updateStatus(`Errore collegamento: ${err.message}`);return false}}
    async ensureWritePermission(h){if(!h)return false;try{if(await h.queryPermission({mode:'readwrite'})==='granted')return true;return await h.requestPermission({mode:'readwrite'})==='granted'}catch(_){return false}}
    async saveCurrentJSON(){const id=this.game.areaId;let h=this.fileHandles[id];if(!h){const ok=await this.linkJSON();if(!ok)return;h=this.fileHandles[id]}if(!await this.ensureWritePermission(h)){this.els.saveState.className='save-state error';this.els.saveState.textContent='Impossibile scrivere il file';this.updateStatus('Permesso di scrittura non concesso');return}try{const w=await h.createWritable();await w.write(JSON.stringify(this.collisionJSON(),null,2));await w.close();localStorage.setItem(`esposizione-editor-area-${id}`,JSON.stringify(this.collisionJSON()));this.setDirty(false);this.refreshFileState();this.updateStatus(`${h.name} aggiornato direttamente`)}catch(err){this.els.saveState.className='save-state error';this.els.saveState.textContent='Errore salvataggio';this.updateStatus(`Errore salvataggio: ${err.message}`)}}
    refreshFileState(){if(!this.els.fileState)return;const h=this.fileHandles[this.game.areaId];this.els.fileState.textContent=h?`JSON collegato: ${h.name}`:'JSON: non collegato'}

    updateStatus(s){this.els.status.textContent=s}
    draw(c){if(!this.enabled)return;this.refreshMeta();this.refreshFileState();c.save();const z=this.game.viewZoom||1;c.lineWidth=3/z;
      if(this.visibility.collisions){c.strokeStyle='#ffe96b';c.fillStyle='#ffe96b';for(const p of this.draft){c.beginPath();c.arc(p[0],p[1],7/z,0,Math.PI*2);c.fill()}if(this.draft.length){c.beginPath();this.draft.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.stroke()}const a=this.game.area;c.fillStyle='#fff';for(const poly of a.walkable||[])for(const p of poly){c.beginPath();c.arc(p[0],p[1],5/z,0,Math.PI*2);c.fill()}c.fillStyle='#ff8b8b';for(const o of a.obstacles||[])if(o.type==='poly')for(const p of o.points){c.beginPath();c.arc(p[0],p[1],5/z,0,Math.PI*2);c.fill()}}
      if(this.selected?.obj?.points&&Number.isInteger(this.selected.vertex)){const p=this.selected.obj.points[this.selected.vertex];c.strokeStyle='#ffe96b';c.lineWidth=4/z;c.beginPath();c.arc(p[0],p[1],10/z,0,Math.PI*2);c.stroke()}
      if(this.selected?.group==='decor'){const o=this.selected.obj,b=this.decorBounds(o);c.strokeStyle='#35d7ff';c.lineWidth=3/z;c.setLineDash([8/z,5/z]);c.strokeRect(b.x,b.y,b.w,b.h);c.setLineDash([]);c.strokeStyle='#ffe96b';c.lineWidth=4/z;c.beginPath();c.moveTo(b.x-16/z,o.y);c.lineTo(b.x+b.w+16/z,o.y);c.stroke();c.fillStyle='#ffe96b';c.beginPath();c.arc(o.x,o.y,7/z,0,Math.PI*2);c.fill()}
      if(this.selected?.group==='gate'){const g=this.selected.obj;c.strokeStyle='#fff36e';c.lineWidth=5/z;c.strokeRect(g.x,g.y,g.w,g.h)}
      if(this.selected?.group==='hotspot'){const h=this.selected.obj;c.strokeStyle='#fff36e';c.lineWidth=4/z;c.beginPath();c.arc(h.x,h.y,h.r||110,0,Math.PI*2);c.stroke()}
      c.restore()}
  }
  window.EsposizioneEditor=Editor;
})();
