(function(){'use strict';
 const $=s=>document.querySelector(s);
 const ITEMS=[{"id": "biglietto_area_nord", "category": "documents", "name": "Biglietto Area Nord", "description": "Biglietto d'ingresso valido per l'Area Nord. Include un ombrello omaggio e 100 Lire dell'Esposizione.", "status": "Valido", "action": "Esamina", "icon": "🎟", "image": "images/ui/inventory/items/documents/biglietto_area_nord.png"}, {"id": "mappa_esposizione", "category": "useful", "name": "Mappa dell'Esposizione", "description": "Pianta dell’Esposizione per orientarsi tra padiglioni, viali e attrazioni.", "status": "Disponibile", "action": "Consulta", "icon": "🗺", "image": "images/ui/inventory/items/useful/mappa_esposizione.png"}, {"id": "ombrello_omaggio", "category": "gadgets", "name": "Ombrello omaggio", "description": "Un ombrello ricordo consegnato assieme al biglietto dell'Area Nord.", "status": "In possesso", "action": "Esamina", "icon": "☂", "image": "images/ui/inventory/items/gadgets/ombrello_omaggio.png"}, {"id": "moneta_benvenuto", "category": "collectibles", "name": "Moneta di benvenuto", "description": "Moneta commemorativa della visita all'Esposizione, da conservare nella collezione.", "status": "Raccolta", "action": "Osserva", "icon": "🪙", "image": "images/ui/inventory/items/collectibles/moneta_benvenuto.png"}, {"id": "chiave_area_sud", "category": "missions", "name": "Chiave misteriosa", "description": "Una chiave trovata per terra. Potrebbe aprire qualcosa nell'Area Sud.", "status": "Da usare", "action": "Esamina", "icon": "🗝", "image": "images/ui/inventory/items/missions/chiave_area_sud.png"}];
 const CATS=[['documents','Documenti','▤'],['useful','Oggetti utili','⌖'],['gadgets','Gadget','✦'],['collectibles','Collezionabili','◈'],['missions','Missioni','⚿']];
 const KEY='esposizione_inventory_v1'; const defaults=()=>({version:1,points:100,lire:100,owned:ITEMS.map(x=>x.id)});
 function load(){try{const d=JSON.parse(localStorage.getItem(KEY));return d&&Array.isArray(d.owned)&&Number.isFinite(d.points)&&Number.isFinite(d.lire)?d:defaults()}catch(_){return defaults()}}
 let state=load(),category='documents',opened=false,detail=null;
 const overlay=$('#inventoryOverlay'),detailLayer=$('#inventoryDetail');
 function store(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(err){console.warn('Inventario: salvataggio locale non disponibile',err)}}
 function illustration(item,large=false){const box=document.createElement('div');box.className='inventory-item-art'+(large?' big':'');const icon=document.createElement('span');icon.textContent=item.icon;box.appendChild(icon);const image=new Image();image.alt='';image.loading='lazy';image.onload=()=>{box.replaceChildren(image)};image.src=item.image;return box}
 function render(){ $('#inventoryPoints').textContent=state.points.toLocaleString('it-IT');$('#inventoryLire').textContent=state.lire.toLocaleString('it-IT');
 const tabs=$('#inventoryCategories');tabs.replaceChildren();for(const [id,label,icon] of CATS){const b=document.createElement('button');b.type='button';b.className=id===category?'selected':'';b.textContent=icon+' '+label;b.setAttribute('aria-pressed',String(id===category));b.onclick=()=>{category=id;render()};tabs.appendChild(b)}
 const grid=$('#inventoryGrid');grid.replaceChildren();const list=ITEMS.filter(x=>x.category===category&&state.owned.includes(x.id));if(!list.length){const p=document.createElement('p');p.textContent='Nessun oggetto in questa categoria.';grid.appendChild(p)}for(const item of list){const b=document.createElement('button');b.className='inventory-slot';b.type='button';b.append(illustration(item));const name=document.createElement('span');name.textContent=item.name;b.appendChild(name);b.onclick=()=>openDetail(item);grid.appendChild(b)}}
 function open(){if(opened||!window.EsposizioneInventoryCanOpen?.())return;opened=true;category='documents';detail=null;detailLayer.hidden=true;overlay.hidden=false;window.EsposizioneInventoryGame?.()?.setPaused(true);render();$('#inventoryClose').focus()}
 function close(){if(!opened)return;opened=false;detail=null;detailLayer.hidden=true;overlay.hidden=true;window.EsposizioneInventoryGame?.()?.setPaused(false)}
 function openDetail(item){detail=item;$('#inventoryDetailName').textContent=item.name;$('#inventoryDetailCategory').textContent=CATS.find(c=>c[0]===item.category)?.[1]||'';$('#inventoryDetailDescription').textContent=item.description;$('#inventoryDetailStatus').textContent='Stato: '+item.status;$('#inventoryDetailImage').replaceChildren(illustration(item,true));$('#inventoryAction').textContent=item.action;detailLayer.hidden=false;$('#inventoryDetailClose').focus()}
 function closeDetail(){detail=null;detailLayer.hidden=true;$('#inventoryClose').focus()}
 $('#inventoryPlayerBtn').onclick=open;$('#inventoryAdminBtn').onclick=open;$('#inventoryClose').onclick=close;$('#inventoryDetailClose').onclick=closeDetail;$('#inventoryBack').onclick=closeDetail;
 $('#inventoryAction').onclick=()=>{if(!detail)return;const status=detail.action==='Consulta'?'La mappa dettagliata sarà disponibile in una prossima versione.':'Oggetto esaminato. Le interazioni saranno disponibili nelle prossime versioni.';window.alert(status)};
 window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i'&&!e.repeat&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();if(opened)close();else open()}else if(e.key==='Escape'&&opened){e.preventDefault();e.stopImmediatePropagation();if(!detailLayer.hidden)closeDetail();else close()}},true);
 window.addEventListener('esposizione:inventory-start',e=>{if(opened)close();if(e.detail?.newGame){state=defaults();store()}else state=load()});
 window.EsposizioneInventory={open,close,isOpen:()=>opened,getState:()=>structuredClone(state),addItem(id){if(!ITEMS.some(x=>x.id===id))return false;if(!state.owned.includes(id)){state.owned.push(id);store();if(opened)render()}return true},addPoints(n){if(!Number.isFinite(n))return;state.points=Math.max(0,state.points+n);store();if(opened)render()},addLire(n){if(!Number.isFinite(n))return;state.lire=Math.max(0,state.lire+n);store();if(opened)render()}};
})();
